# /system/etc/bash.bashrc
#
# This is the user file for bashrc sourced by all interactive bash shells
# Customize however you want

echo "bash.bashrc as $(whoami)" >> /sdcard/bash_log

DIRECTORY=/system/etc/bash_completion.d

if [  -d "$DIRECTORY" ]; then
  for filename in $DIRECTORY/*; do
      source $filename
  done
fi


[ -f "/sdcard/.bashrc" ] && . /sdcard/.bashrc 
